import {
  ScanBarcode,
  ChartNoAxesCombined,
  ArrowDown10,
  Eye,
  Palette,
  Blocks,
  LayersPlus,
  Package,
  FilePlus,
  HandCoins,
  Pencil,
  ScanText,
  Store,
  ChartColumnStacked,
  Banknote,
  BanknoteArrowUp,
  BanknoteArrowDown,
  PiggyBank,
  Shirt,
  ShieldCheck,
  Mail,
  LockKeyhole,
} from 'lucide-react'

export const iconMap = {
  lockKeyhole: LockKeyhole,
  mail: Mail,
  scanText: ScanText,
  pencil: Pencil,
  store: Store,
  category: ChartColumnStacked,
  banknote: Banknote,
  banknoteArrowUp: BanknoteArrowUp,
  bankNoteArrowDown: BanknoteArrowDown,
  piggyBank: PiggyBank,
  handCoins: HandCoins,
  filePlus: FilePlus,
  shirt: Shirt,
  package: Package,
  layersPlus: LayersPlus,
  noIcon: null,
  blocks: Blocks,
  color: Palette,
  eye: Eye,
  stock: ArrowDown10,
  chartNoAxesCombined: ChartNoAxesCombined,
  scanBarCode: ScanBarcode,
  shieldCheck: ShieldCheck,
} as const

export type IconName = keyof typeof iconMap
